export const titulo = [
  { label: "Número de portal", value: "portal" },
  { label: "Tramos viales", value: "tramosV" },
  { label: "Parking", value: "parking" },
  { label: "Vias1", value: "Vias1" },
  { label: "Vias2", value: "Vias2" },
  { label: "Vias3", value: "Vias3" },
  { label: "Vias4", value: "Vias4" },
];

export const keyWord = [
  { label: "Portal", value: "portal" },
  { label: "Numero", value: "numero" },
  { label: "Calles", value: "calles" },
  { label: "Tramos Viales", value: "tramos_viales" },
  { label: "Vias", value: "vias" },
  { label: "Parking", value: "parking" },
  { label: "Aparcamiento", value: "aparcamiento" },
];

export const formato = [
  { label: "Shape", value: "shape" },
  { label: "GeoJSON", value: "geoJson" },
  { label: "KML", value: "kml" },
  { label: "CSV", value: "csv" },
  { label: "GML 3.2", value: "gml3.2" },
];

export const DatosTable = [
  {
    title: "Número de portal",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Portal, Numero, Calles",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Tramos viales",
    creado: "2024/05/13",
    formato: "GeoJSON",
    keyword: "Tramos Viales, Vias, Aparcamiento",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Parking",
    creado: "2024/05/13",
    formato: "KML",
    keyword: "Parking, Aparcamiento",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias1",
    creado: "2024/05/13",
    formato: "CSV",
    keyword: "Vias",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias2",
    creado: "2024/05/13",
    formato: "GML 3.2",
    keyword: "Vias, Calles",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias3",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Numero, Portal",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias4",
    creado: "2024/05/13",
    formato: "GeoJSON",
    keyword: "Calles, Tramos Viales",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Número de portal",
    creado: "2024/05/13",
    formato: "CSV",
    keyword: "Portal, Numero, Parking",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Tramos viales",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Tramos Viales, Vias",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Parking",
    creado: "2024/05/13",
    formato: "GML 3.2",
    keyword: "Parking, Aparcamiento, Vias",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias1",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Vias, Numero",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias2",
    creado: "2024/05/13",
    formato: "KML",
    keyword: "Vias, Calles, Tramos Viales",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias3",
    creado: "2024/05/13",
    formato: "CSV",
    keyword: "Vias, Numero, Portal",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias4",
    creado: "2024/05/13",
    formato: "GML 3.2",
    keyword: "Calles, Tramos Viales, Parking",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Número de portal",
    creado: "2024/05/13",
    formato: "GeoJSON",
    keyword: "Portal, Aparcamiento, Tramos Viales",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Parking",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Parking, Calles, Numero",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias1",
    creado: "2024/05/13",
    formato: "GML 3.2",
    keyword: "Vias, Tramos Viales, Portal",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias2",
    creado: "2024/05/13",
    formato: "GeoJSON",
    keyword: "Vias, Calles, Parking",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias3",
    creado: "2024/05/13",
    formato: "CSV",
    keyword: "Vias, Numero, Aparcamiento",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Vias4",
    creado: "2024/05/13",
    formato: "Shape",
    keyword: "Calles, Tramos Viales, Numero",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Número de portal",
    creado: "2024/05/13",
    formato: "KML",
    keyword: "Portal, Calles, Vias",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
  {
    title: "Tramos viales",
    creado: "2024/05/13",
    formato: "GML 3.2",
    keyword: "Tramos Viales, Numero, Aparcamiento",
    vizualizar: "Vizualizar",
    descargar: "Descargar",
    ver: "Ver",
  },
];

export const Tema = [
  { label: "Tema 1", value: "tema1" },
  { label: "Tema 2", value: "tema2" },
  { label: "Tema 3", value: "tema3" },
  { label: "Tema 4", value: "tema4" },
  { label: "Tema 5", value: "tema5" },
];
export const Creado = [
  { label: "13/05/2024", value: "1" },
  { label: "04/06/2024", value: "2" },
  { label: "05/06/2024", value: "3" },
  { label: "06/06/2024", value: "4" },
  { label: "07/06/2024", value: "5" },
];
